// [filename]  README

============================================================
                          README
============================================================

This is a README file generated by VMMGEN template generator.
The generated directory structure and template files by VMMGEN are shown here.

User need to fill required code wherever "ToDO: ". 
The generated code can be compiled with the following versions:
- Synopsys VCS Version C-2009.12 and later versions
- VMM 1.2 

*************************************************************
STEPS TO COMPILE AND RUN EXAMPLE
*************************************************************
vmmgen/proj/VNAME/run $ make

Note: 
  1) To include the VMM inbuilt source from VCS installation:
     Inclusion of VMM_HOME can be replaced by -ntb_opts rvm command in Makefile
  2) To use the VMM source other than VCS installation directory:
     Set environment variable VMM_HOME to the vmm-1.2 installation directory

*************************************************************
Directory Structure of environment generated by VMMGEN
*************************************************************
-proj
  |
  -README
  |
  -VNAME
       |
       -doc/
       |
       -examples/
       |
       -hdl/        ---> includes top module and inclusion of all environment files.
       |
       | - VNAME_top.sv 
       | - VNAME.sv
       |
       -env/        ---> includes environment related files (environment, ralenv)
       |  ENFILES
       |
       -include/
       |
       -src/        ---> includes Transaction, configurations, driver, monitor, master/slave subenv, scoreboard, coverage related files.
       |  SRCFILES
       |
       -tests/      ---> includes program block and testcases 
       |
       | - VNAME_prog.sv 
       | - VNAME_test.sv
       |
       -run/        ---> Makefile

